export const ActionTypes = {
  SET_MESSAGE: "SET_MESSAGE",
  CLEAR_MESSAGE: "CLEAR_MESSAGE",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  REMOVE_TASK: "REMOVE_TASK",
  ADD_TASK: "ADD_TASK",
  EDIT_TASK: "EDIT_TASK",
  LOADING: "LOADING",
};
